[profile.default]
src = "src"
out = "out"
libs = ["node_modules","lib"]

remappings=[
    '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip',
    '@chainlink/brownie/=lib/chainlink-brownie-contracts/contracts/src/v0.8/',
    '@chainlink/local/=lib/chainlink-local/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
